### ISSUE TITLE
karma: Failed: Unexpected value '[object Object]' declared by the module 'DynamicTestModule'

### ISSUE THREAD

**Issue by TheShanMan** [gund/ng-dynamic-component#147]
Background: I was getting the following error when running ng test:

`Failed: Template parse errors:
Can't bind to 'ndcDynamicInputs' since it isn't a known property of 'div'. ("h4>{{panel.title}}</h4>
<div *ngIf="panel.header" class="header" [ngComponentOutlet]="panel.header" [ERROR ->][ndcDynamicInputs]="{panel: panel}"></div>
<div class="padded">
  <ng-container [ngComponentOutlet]=""): ng:///DynamicTestModule/ContentPanelComponent.html@1:76
Can't bind to 'ndcDynamicInputs' since it isn't a known property of 'ng-container'.
1. If 'ndcDynamicInputs' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("="{panel: panel}"></div>
<div class="padded">
  <ng-container [ngComponentOutlet]="panel.component" [ERROR ->][ndcDynamicInputs]="{panel: panel}"></ng-container>
</div>
"): ng:///DynamicTestModule/ContentPanelComponent.html@3:54
`

I then added DynamicModule.withComponents([]) to my TestBed declarations:

`  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent, GroupHorizontalPanelComponent, GroupVerticalPanelComponent, ContentPanelComponent, TickerComponent, DynamicModule.withComponents([])
      ],
    }).compileComponents();
  }));
`

Now I get:

`Failed: Unexpected value '[object Object]' declared by the module 'DynamicTestModule'
Error: Unexpected value '[object Object]' declared by the module 'DynamicTestModule'
    at syntaxError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:486:22)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:15280:1
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp../node_modules/@angular/compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:15278:1)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/esm5/compiler.js.JitCompiler._loadModules (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:34413:58)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:34391:1)
    at JitCompiler.webpackJsonp../node_modules/@angular/compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/esm5/compiler.js:34290:1)
    at CompilerImpl.webpackJsonp../node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:269:1)
    at TestingCompilerImpl.webpackJsonp../node_modules/@angular/platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:341:1)
    at TestBed.webpackJsonp../node_modules/@angular/core/esm5/testing.js.TestBed.compileComponents (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/testing.js:968:1)
`

Here are my dependencies and devDependencies:

`  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular-l10n": "^4.1.5",
    "core-js": "^2.4.1",
    "ng-dynamic-component": "^2.3.0",
    "rxjs": "^5.5.6",
    "velocity-animate": "^1.5.1",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
`

What do I need to do?

**Comment by TheShanMan** [comment]
Sorry it didn't format the stuff I pasted into the "code" sections.

**Comment by gund** [comment]
@TheShanMan you should put the module in the import section and not declare.
