### ISSUE TITLE
Universal node startup error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by swaner** [gund/ng-dynamic-component#186]
After upgrading ng-dynamic-component from version 3.0.0 to version 3.1.0.
Running using ng serve works fine, but when using node and server side rendering I get the error directly on startup so server won't event start up.

Seems to be related to DynamicAttributesDirective, the compiled row it crashes on is:
```
/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
var Reflect = (window).Reflect;
```

This is the entire call stack:
```
var Reflect = (window).Reflect;
              ^

ReferenceError: window is not defined
    at Module.Object.defineProperty.value (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:187825:15)
    at __webpack_require__ (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:20:30)
    at Object.ng-dynamic-component (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:165379:18)
    at __webpack_require__ (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:151061:30)
    at Object../node_modules/ng-dynamic-component/ng-dynamic-component.ngfactory.js (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:152949:10)
    at __webpack_require__ (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:151061:30)
    at Object../src/app/cms/app.component.ngfactory.js (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:157972:10)
    at __webpack_require__ (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:151061:30)
    at Object../src/app/cms/cms.module.ngfactory.js (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:158128:10)
    at __webpack_require__ (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:151061:30)
    at Object../src/main.server.ts (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:165000:18)
    at __webpack_require__ (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:151061:30)
    at Object.0 (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:165015:18)
    at __webpack_require__ (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:151061:30)
    at /Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:151125:18
    at Object.<anonymous> (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:151128:10)
    at __webpack_require__ (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:20:30)
    at Object.<anonymous> (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:117:10)
    at __webpack_require__ (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:20:30)
    at Object.defineProperty.value (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:84:18)
    at Object.<anonymous> (/Users/myuser/dev/myproject/Coursify.Angular/dist/server.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by gund** [comment]
Hi, yes it is the cause of the crash indeed. I will fix this.

**Comment by swaner** [comment]
@gund Thanks for the quick fix. Seems to work just fine now 👍 :)
