### ISSUE TITLE
Bug Error Angular 9 | Importing DynamicComponentModule which does not have a ɵmod property

### ISSUE THREAD

**Issue by GlauberF** [gund/ng-dynamic-component#371]
```
polyfills.js:4039 Unhandled Promise rejection: Importing DynamicComponentModule which does not have a ɵmod property ; Zone: <root> ; Task: Promise.then ; Value: Error: Importing DynamicComponentModule which does not have a ɵmod property
    at vendor.js:104738
    at Array.forEach (<anonymous>)
    at transitiveScopesFor (vendor.js:104729)
    at vendor.js:104743
    at Array.forEach (<anonymous>)
    at transitiveScopesFor (vendor.js:104729)
    at vendor.js:104743
    at Array.forEach (<anonymous>)
    at transitiveScopesFor (vendor.js:104729)
    at setScopeOnDeclaredComponents (vendor.js:104639) Error: Importing DynamicComponentModule which does not have a ɵmod property
    at http://localhost:4200/vendor.js:104738:19
    at Array.forEach (<anonymous>)
    at transitiveScopesFor (http://localhost:4200/vendor.js:104729:32)
    at http://localhost:4200/vendor.js:104743:31
    at Array.forEach (<anonymous>)
    at transitiveScopesFor (http://localhost:4200/vendor.js:104729:32)
    at http://localhost:4200/vendor.js:104743:31
    at Array.forEach (<anonymous>)
    at transitiveScopesFor (http://localhost:4200/vendor.js:104729:32)
    at setScopeOnDeclaredComponents (http://localhost:4200/vendor.js:104639:30)
```

I tested using the versions:
ng-dynamic-component@^6.0.0
ng-dynamic-component@^6.1.0
ng-dynamic-component@6.1.1-no-barrels.2

Angular:
```
Angular CLI: 9.1.3
Node: 10.15.3
OS: linux x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.3
@angular-devkit/build-angular      0.901.3
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.3
@angular-devkit/core               9.1.3
@angular-devkit/schematics         9.1.3
@angular/cdk                       9.2.1
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.1
@angular/material-moment-adapter   9.2.1
@ngtools/webpack                   9.1.3
@nguniversal/builders              9.1.0
@nguniversal/common                9.1.0
@nguniversal/express-engine        9.1.0
@schematics/angular                9.1.3
@schematics/update                 0.901.3
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

**Comment by gund** [comment]
Hi, does this error happen only when you import `DynamicComponentModule` or for other modules as well?

**Comment by GlauberF** [comment]
only when I import DynamicComponentModule

**Comment by GlauberF** [comment]
@gund any news to fix the problem?

**Comment by GlauberF** [comment]
Hello @gund, I'm closing because the error was in the way that I imported the modules.

Even if you have a solution.
I have an index.ts that exports all the components, so inside where I'm going to use the ng-dynamic-component, I call:
`import * as components from '. /component/index.ts'`

so supposing I want to use the component, badge, declare like this:
`[ngComponentOutlet] ="components['Badge']"`

but these ways does not work and gives the error mentioned above, if I import the Badge component directly and use, then it works.

I would have some idea, because as it is dynamic, I have to make available all the components to be used and to be importing one by one, of the work.
More than work, when creating a new component, I have to remember to import
