### ISSUE TITLE
ERROR in Error: Internal error: unknown identifier undefined

### ISSUE THREAD

**Issue by willyboy** [gund/ng-dynamic-component#408]
Hi, 
When trying to build with AOT, I receive the following error
```
ERROR in Error: Internal error: unknown identifier undefined
    at Object.importExpr$1 [as importExpr] (/node_modules/@angular/compiler/bundles/compiler.umd.js:27262:27)
    at tokenExpr (/node_modules/@angular/compiler/bundles/compiler.umd.js:23761:43)
    at providerDef (/node_modules/@angular/compiler/bundles/compiler.umd.js:23687:24)
    at ViewBuilder._visitProviderOrDirective (/node_modules/@angular/compiler/bundles/compiler.umd.js:25224:22)
    at ViewBuilder._visitProvider (/node_modules/@angular/compiler/bundles/compiler.umd.js:25186:40)
    at /node_modules/@angular/compiler/bundles/compiler.umd.js:25048:27
    at Array.forEach (<anonymous>)
    at ViewBuilder._visitElementOrTemplate (/node_modules/@angular/compiler/bundles/compiler.umd.js:25035:27)
    at ViewBuilder.visitElement (/node_modules/@angular/compiler/bundles/compiler.umd.js:24955:27)
    at ElementAst.visit (/node_modules/@angular/compiler/bundles/compiler.umd.js:11821:28)
    at visit (/node_modules/@angular/compiler/bundles/compiler.umd.js:11999:41)
    at /node_modules/@angular/compiler/bundles/compiler.umd.js:12001:29
    at Array.forEach (<anonymous>)
    at templateVisitAll (/node_modules/@angular/compiler/bundles/compiler.umd.js:12000:14)
    at ViewBuilder.visitAll (/node_modules/@angular/compiler/bundles/compiler.umd.js:24829:13)
    at ViewCompiler.compileComponent (/node_modules/@angular/compiler/bundles/compiler.umd.js:24767:21)
```

## Command run
```
ng build --project=myapp --aot=true
```
## Library version
```
6.1.1-no-barrels.2
```
## App code
Note! issues exists simply by referencing import {} from 'ng-dynamic-component' even if it doesn't import anything.
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import {
  DynamicComponentModule,
  DynamicAttributesModule,
  DynamicIoModule,
  DynamicDirectivesModule,
} from 'ng-dynamic-component';
@NgModule({
  declarations: [],
  imports: [BrowserModule, DynamicComponentModule, DynamicAttributesModule, DynamicIoModule, DynamicDirectivesModule],
  providers: []
})
export class AppModule {}
```

Happy to drop a PR if you have an idea of what's causing this.

**Comment by willyboy** [comment]
Ooops, I missed this one https://github.com/gund/ng-dynamic-component/issues/377
