### ISSUE TITLE
Support for Angular 16

### ISSUE THREAD

**Issue by ankurrai2602** [gund/ng-dynamic-component#512]
Can you update ng-dynamic-component to support Angular 16, please?

**Comment by ankurrai2602** [comment]
Getting below error when using in Angular16

main.ts:21 TypeError: def.findHostDirectiveDefs is not a function
    at findDirectiveDefMatches (core.mjs:12708:29)
    at resolveDirectives (core.mjs:12492:29)
    at elementStartFirstCreatePass (core.mjs:16277:5)
    at ɵɵelementStart (core.mjs:16313:9)
    at Module.ɵɵelement (core.mjs:16394:5)
    at AppComponent_Template (app.component.html:13:1)
    at executeTemplate (core.mjs:12003:13)
    at renderView (core.mjs:13201:13)
    at renderComponent (core.mjs:13148:5)
    at renderChildComponents (core.mjs:13246:9)

**Comment by gund** [comment]
It does not seem like this error has anything to do with this library.
Also this library fully compatible with Angular 16 and does not require any changes as Angular did not introduce any breaking changes since v14.
There were [similar issues](https://github.com/gund/ng-dynamic-component/issues/493) reported previously but they had nothing to do with this library.
Please double check your errors and project setup and if it is actually related post relevant error that points to the code from this library, ideally you should create online repro that shows the error as this will help resolve this issue faster.

**Comment by ankurrai2602** [comment]
I tested a fresh ng16 project, it's working fine. However, there may be another issue causing the error in my project.
